### ISSUE TITLE
Profile word usage confusing?

### ISSUE THREAD

**Issue by adurbin-rivos** [riscv-admin/control-transfer-records#1]
Mark Himelstein indicated through email that the use of 'profiles' is confusing. He suggested the following:

can we at least say "(not ISA profiles)"?

**Comment by bcstrongx** [comment]
I changed all references to "profiles" to instead say "instruction profiles", save for the reference to profile-guided optimizations, since PGO is an industry standard term.  Is that sufficient to to eliminate any confusion?

**Comment by jrtc27** [comment]
"execution profiles" would seem better and broader in order to cover a wider range of (micro)architectural performance counters

**Comment by jjscheel** [comment]
@mark-riscv, would "execution profiles" help?

**Comment by mark-riscv** [comment]
The issue is that many people reading the proposal are neither sw or toolchain folks. If you define execution profiles as tools/runtime related and not related to ISA-profiles then I am good. If not, it once again, in my opinion, leaves them to figure out what this means. So I suggets pick whatever language you want and just add a one line note saying whatever nomenclature you pick has no relationship to ISA profiles.

**Comment by bcstrongx** [comment]
First sentence now reads: "Profile-guided optimization tools, such as autofdo, depend on accurate execution profiles (not to be confused with ISA profiles) to guide compilation and effect performance improvements."

**Comment by mark-riscv** [comment]
perfect--------sent from a mobile device. please forgive any typos.On Feb 17, 2023, at 9:02 AM, Beeman Strong ***@***.***> wrote:﻿
First sentence now reads: "Profile-guided optimization tools, such as autofdo, depend on accurate execution profiles (not to be confused with ISA profiles) to guide compilation and effect performance improvements."
